name: Docs
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
      - name: Verify lockfile is in sync
        run: uv lock --locked
      - name: Build site
        run: |
          uv run zensical build --clean
          uv run zensical build -f ./en-zensical.toml
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
          if-no-files-found: error

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: site
          path: site
      - run: echo 'security.ocf.tw' > ./site/CNAME
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - id: deployment
        uses: actions/deploy-pages@v5
